#ifndef mitk_command_def_h__
#define mitk_command_def_h__

#define MITK_MAIN_COMMAND_LOADDATA          "MITK_MAIN_COMMAND_LOADDATA"
#define MITK_MAIN_COMMAND_ENABLE_VTK_WARNING    "MITK_MAIN_COMMAND_ENABLE_VTK_WARNING"
#define MITK_MAIN_COMMAND_CHANGE_CROSSHAIR_GAP_SIZE  "MITK_MAIN_COMMAND_CHANGE_CROSSHAIR_GAP_SIZE"
#endif // mitk_command_def_h__
