#ifndef mitk_command_def_h__
#define mitk_command_def_h__

#define MITK_MAIN_COMMAND_LOADDATA          "MITK_MAIN_COMMAND_LOADDATA"
#define MITK_MAIN_COMMAND_ENABLE_VTK_WARNING    "MITK_MAIN_COMMAND_ENABLE_VTK_WARNING"
#define MITK_MAIN_COMMAND_CHANGE_CROSSHAIR_GAP_SIZE  "MITK_MAIN_COMMAND_CHANGE_CROSSHAIR_GAP_SIZE"
#define MITK_MAIN_COMMAND_VOLUME_VISUALIZATION "MITK_MAIN_COMMAND_VOLUME_VISUALIZATION"
#define MITK_MAIN_COMMAND_CHANGE_MULTIVIEW_LAYOUT "MITK_MAIN_COMMAND_CHANGE_MULTIVIEW_LAYOUT"
#define MITK_MAIN_COMMAND_RESET_MULTIVIEW "MITK_MAIN_COMMAND_RESET_MULTIVIEW"
#endif // mitk_command_def_h__
